---
name: release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read       # checkout the repo
      packages: write      # push to GHCR

    runs-on: ubuntu-24.04
    name: Build and Push new docker image
    steps:
      - id: source-checkout
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: main

      - id: ghcr-io-login
        name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: deployment-test
        name: Run deployment test
        run: ./test.sh --release
        shell: bash

      - id: build-push-image
        name: Build and Push netbox docker image
        run: ./build.sh --push
        shell: bash
