---
name: release

on:
  release:
    types:
      - published
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build and Push new docker image
    steps:
      - id: source-checkout
        name: Checkout
        uses: actions/checkout@v5
        with:
          ref: main

      - id: ghcr-io-login
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - id: build-push-image
        name: Build and Push netbox docker image
        run: ./build.sh --push
        shell: bash
