---
name: test

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - netbox_version.env
      - plugin_requirements.txt

      - configuration/**
      - docker-compose*.yml
      - Dockerfile
      - test.sh

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Run a deployment test with the netbox image
    steps:
      - id: source-checkout
        name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - id: test-netbox-deployment
        name: Test the Netbox deployment
        run: ./test.sh
        shell: bash
